name: Update headlines.json

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-headlines
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Sync to origin/main
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin main
          git reset --hard origin/main

      - name: Generate headlines.json
        shell: bash
        run: |
          set -euo pipefail
          python update_headlines.py

      # Force meta.generated_at to "now" so a successful run always produces a diff.
      # (If the generator already updated it, this just reaffirms it.)
      - name: Force bump generated_at (ensures diff)
        shell: bash
        run: |
          set -euo pipefail
          python - << 'PY'
          import json
          from datetime import datetime, timezone
          p = "headlines.json"
          with open(p, "r", encoding="utf-8") as f:
            data = json.load(f)
          data.setdefault("meta", {})
          data["meta"]["generated_at"] = datetime.now(timezone.utc).isoformat()
          with open(p, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
          print("generated_at now:", data["meta"]["generated_at"])
          PY

      - name: Show meta in logs
        shell: bash
        run: |
          set -euo pipefail
          python - << 'PY'
          import json
          with open("headlines.json","r",encoding="utf-8") as f:
            d=json.load(f)
          print("meta:", d.get("meta"))
          for k in ["breaking","developing","nothingburger","world","politics","markets","tech","weird","missed"]:
            print(k, "count:", len((d.get("sections") or {}).get(k, [])))
          PY

      - name: Commit & push (retry-safe, no rebase)
        shell: bash
        run: |
          set -euo pipefail

          git config user.name "dailysideeye-bot"
          git config user.email "actions@users.noreply.github.com"

          git add headlines.json

          if git diff --cached --quiet; then
            echo "No changes after generation + bump (unexpected)."
            exit 0
          fi

          git commit -m "Update headlines.json ($(date -u '+%Y-%m-%d %H:%M UTC'))"

          for attempt in 1 2 3; do
            if git push; then
              exit 0
            fi
            echo "Push failed (attempt $attempt). Re-sync and retry..."

            git fetch origin main
            git reset --hard origin/main

            python update_headlines.py

            python - << 'PY'
            import json
            from datetime import datetime, timezone
            p="headlines.json"
            with open(p,"r",encoding="utf-8") as f:
              data=json.load(f)
            data.setdefault("meta",{})
            data["meta"]["generated_at"]=datetime.now(timezone.utc).isoformat()
            with open(p,"w",encoding="utf-8") as f:
              json.dump(data,f,ensure_ascii=False,indent=2)
            PY

            git add headlines.json
            if git diff --cached --quiet; then
              echo "After resync, nothing to push."
              exit 0
            fi
            git commit -m "Update headlines.json ($(date -u '+%Y-%m-%d %H:%M UTC'))"
          done

          echo "Push failed after retries."
          exit 1
