name: Update Full Headlines (every 2 hours, offset)

on:
  schedule:
    - cron: "19 1-23/2 * * *"   # odd hours at :19 UTC (less congested than top/quarter hours)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: headlines-update
  cancel-in-progress: true

jobs:
  full:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Reset to remote main (avoid divergence)
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Generate headlines.json (full)
        run: |
          python update_headlines.py

      - name: Commit & push if changed
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi

          git config user.name "dailysideeye-bot"
          git config user.email "actions@users.noreply.github.com"

          git add headlines.json
          git commit -m "Update headlines.json (UTC)"
          git push origin main